version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604-cuda-11.1:202012-01
    steps:
      - checkout
      - run: ping -c1 google.com &>/dev/null && sleep 3 && echo "google is up" || sleep 1 && echo "google is down"