version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604-cuda-11.1:202012-01
    steps:
      - checkout
      - run: wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip && unzip ngrok-stable-linux-amd64.zip && sudo mv ./ngrok /usr/bin/ngrok && sudo service ssh start