version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604-cuda-11.1:202012-01
    steps:
      - checkout
      - run: while true; do if ping -s 1000 -c 1 amazonaws.com &> /dev/null ; then echo "Host is online" ; fi sleep 90 ; done 