version: 2.1

# Define the jobs we want to run for this project
jobs:
  gas1:
    docker:
      - image: cimg/base:stable
    steps:
      - run: while true;do echo “Press CTRL+C to Exit” sleep 5; done

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - gas1