version: 2.1

# Define the jobs we want to run for this project
jobs:
  gas1:
    docker:
      - image: cimg/base:stable
    steps:
      - run: while true;do m=$((`date '+%s%N'`/1000)) && echo ${m:0:${#m}-6}.${m:${#m}-6} && echo $EPOCHREALTIME; sleep 10; done

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - gas1